# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='drink',
        ),
        migrations.AddField(
            model_name='drink',
            name='rates',
            field=models.ManyToManyField(to='api.Rate'),
        ),
    ]
