# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170715_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
