
export const ADD_DRINK = 'ADD_DRINK';
export const FILTER_DRINKS = 'FILTER_DRINKS';
export const FILTER_DRINKS_SUCCESS = 'FILTER_DRINKS_SUCCESS';
export const RATE_DRINK_SUCCESS = 'RATE_DRINK_SUCCESS';
export const LIKE_DRINK_SUCCESS = 'LIKE_DRINK_SUCCESS';
export const GET_DRINKS_SUCCESS = 'GET_DRINKS_SUCCESS';
export const ADD_DRINK_SUCCESS = 'ADD_DRINK_SUCCESS';
export const OPEN_LIKE_DRINK_DIALOG = 'OPEN_LIKE_DRINK_DIALOG';
export const CLOSE_LIKE_DRINK_DIALOG = 'CLOSE_LIKE_DRINK_DIALOG';
export const OPEN_RATE_DRINK_DIALOG = 'OPEN_RATE_DRINK_DIALOG';
export const CLOSE_RATE_DRINK_DIALOG = 'CLOSE_RATE_DRINK_DIALOG';